### ISSUE TITLE
Fail to reproduce the results for the semantic entropy method

### ISSUE THREAD

**Issue by jfc43** [lorenzkuhn/semantic_uncertainty#3]
I can roughly reproduce the results for the normalized predictive entropy baseline. However, I fail to reproduce the results for the semantic entropy method and the results I got for the semantic entropy method were slightly worse than the normalized predictive entropy baseline. I find that the implementation of judging whether two answers are equivalent is different from what is described in the paper. In the paper, the description is: "The Deberta model then classifies this sequence into one of: entailment, neutral,
contradiction. We compute both directions, and the algorithm returns equivalent if and only if both directions were entailment." However, in the code, the implementation is: https://github.com/lorenzkuhn/semantic_uncertainty/blob/main/code/get_semantic_similarities.py#L109-L114. It seems the implemented condition is that if both directions are not contradiction. Please check if this is correct or not. Thanks!

**Comment by SebGGruber** [comment]
Hi Lorenz,

any news on this issue? You closed it, but for me, the issue of reproducibility still persists.

Best,
Sebastian
